// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

import (
	"database/sql"
)

type Comment struct {
	ID      uint64
	PostID  sql.NullInt64
	Content sql.NullString
}

type Post struct {
	ID     uint64
	UserID uint64
	Title  sql.NullString
}

type Reply struct {
	ID        uint64
	CommentID sql.NullInt64
	Content   sql.NullString
}

type User struct {
	ID       uint64
	UserName string
}
